### ISSUE TITLE
~

### ISSUE THREAD

**Issue by ac2epsilon** [dportabella/DesktopKeyboard2Android#5]
mvn -e exec:java -Dexec.mainClass="desktopKeyboard2Android.DesktopKeyboard2Android"
- Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] Searching repository for plugin with prefix: 'exec'.
  [INFO] ------------------------------------------------------------------------
  [INFO] Building Unnamed - io.githubdportabella:DesktopKeyboard2Android:jar:1.1-SNAPSHOT
  [INFO]    task-segment: [exec:java]
  [INFO] ------------------------------------------------------------------------
  [INFO] [exec:java {execution: default-cli}]
  [WARNING] 
  java.lang.ClassNotFoundException: desktopKeyboard2Android.DesktopKeyboard2Android
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:281)
  at java.lang.Thread.run(Thread.java:745)
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] An exception occured while executing the Java class. desktopKeyboard2Android.DesktopKeyboard2Android

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: An exception occured while executing the Java class. desktopKeyboard2Android.DesktopKeyboard2Android
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. desktopKeyboard2Android.DesktopKeyboard2Android
    at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:345)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    ... 17 more
Caused by: java.lang.ClassNotFoundException: desktopKeyboard2Android.DesktopKeyboard2Android
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:281)
    at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Mon Nov 30 17:48:20 EET 2015
[INFO] Final Memory: 16M/167M
[INFO] ------------------------------------------------------------------------

**Comment by dportabella** [comment]
I guess you need to run ˋmvn compileˋ before running that command. My laptop is still broken so I cannot test it. Please try it (from scratch, download/clone this project again), and I will update the documentation if this solves the problem.

**Comment by ac2epsilon** [comment]
Yes, of course, David, I anyway know how mvn works, it's kind of "use
strict" kicking. Docs have no glue of compiling while you talk to end
users. Definitelly, compiling SOLVES the problem ) And look, original app
uses 1111 port number, not 7777 so it;s not working out of the git. Also I
see no point for mentioninig port forwarding, it's non-functional sugar
(even not sugar). And.. well, text hard to read cause it's very light. I'm
a Java-kid either, but Java hardly appropriate for this job, as I can see
it. Anyway thank you for.. for 3v3ry7hih9. Ticket closed. ac2.

2015-12-05 8:34 GMT+02:00 David Portabella notifications@github.com:
